// Copies the web client (../public) into www/ for the native shell and bakes in the clinic
// server address. Usage: API_URL=https://clinic.example.ir npm run build:www
// Without API_URL the app asks for the server address on first launch.
import { cpSync, rmSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const root = fileURLToPath(new URL('..', import.meta.url));
const src = fileURLToPath(new URL('../../public', import.meta.url));
const out = `${root}www`;
const apiUrl = (process.env.API_URL || '').replace(/\/$/, '');
if (apiUrl && !/^https?:\/\//.test(apiUrl)) throw new Error('API_URL must start with http:// or https://');

rmSync(out, { recursive: true, force: true });
cpSync(src, out, { recursive: true, filter: (p) => !p.endsWith('sw.js') && !p.endsWith('manifest.webmanifest') });
writeFileSync(`${out}/config.js`, `// generated by mobile/scripts/build-www.mjs\nwindow.TELEHEALTH_API_BASE = ${JSON.stringify(apiUrl)};\n`);
console.log(`www/ built ${apiUrl ? `for ${apiUrl}` : '(server address asked on first launch)'}`);
